apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rollout-2
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 4 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: sujee/nginx:2
          ports:
            - containerPort: 80
